spring:
  datasource:
    url: jdbc:mysql://localhost:3306/train_db_jzy?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456789
  application:
    name: security-server
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            tablePrefix: QRTZ_
            isClustered: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /dietc
  instance:
    preferIpAddress: true
patchcaExpire: 60

